ALTER TABLE users ADD COLUMN timezone TEXT DEFAULT 'UTC';
ALTER TABLE users ADD COLUMN morning_start INTEGER DEFAULT 6;
ALTER TABLE users ADD COLUMN afternoon_start INTEGER DEFAULT 12;
ALTER TABLE users ADD COLUMN evening_start INTEGER DEFAULT 17;
ALTER TABLE users ADD COLUMN night_start INTEGER DEFAULT 21;
